INSERT INTO tags(tag_name)
values('Banquet'),
('Bar Dining'),
('Business Meals'),
('Casual'),
('Creative Cuisine'),
('Corkage Fee'),
('Fit For Foodies'),
('Fun'),
('Full Bar'),
('Good For A Date'),
('Good For Birthdays'),
('Good For Groups'),
('Great For Brunch'),
('Great For Lunch'),
('Healthy'),
('Neighborhood Gem'),
('Non-Smoking'),
('Quick Bite'),
('People Watching'),
('Special Occasion'),
('Wheelchair Access');
